import os

AUTH_URL = 'http://crawler.ritamdigital.org/api/authenticate'
ONLINE_COURSE_GET_PLAYLIST = 'https://crawler.ritamdigital.org/services/crawler/api/online-course-video-playlist'
ONLINE_COURSE_POST_VIDEO = 'https://crawler.ritamdigital.org/services/crawler/api/posts/external/online-course-video/list'

API_KEY = 'AIzaSyAL7YT7XY4HmACZ4rOa-ka92KWm1qSitWw'
YOUTUBE_BASE_URL = 'https://www.youtube.com'

DATE_FORMAT = 'd MMM yyyy HH:mm:ss zzz'


def getHeaders():
    return {'Content-Type': 'application/json'}

def getAuthorizationToken(token):
    return {'Content-Type': 'application/json',
            'Authorization': 'Bearer {}'.format(token)
            }

HEADERS = {
    'Content-type': 'application/json',
    'Authorization': 'Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ0cm1yZWpmdmNnIiwiYXV0aCI6IlJPTEVfQkFBVF9QQVRFX0tJX0VESVRPUixST0xFX0JBRElfQkFBVF9FRElUT1IsUk9MRV9CSEFSQVRfQkhBUlRJX0VESVRPUixST0xFX0JPT0tfUkVWSUVXRVIsUk9MRV9CVUxMRVRJTl9NQU5BR0VNRU5UX0VESVRPUixST0xFX0NPTlRFTlRfRURJVE9SLFJPTEVfREhBUk1BV0lLSV9FRElUT1IsUk9MRV9FRElUT1IsUk9MRV9HQVVSQVZfR0FUSEFfRURJVE9SLFJPTEVfSElTVE9SWV9QQU5FTF9FRElUT1IsUk9MRV9IT01FX1BBR0VfTUFOR0VNRU5ULFJPTEVfSU5URVJWSUVXX1BBTkVMX0VESVRPUixST0xFX0tMSURPU0NPUEVfTUFOQUdFTUVOVF9FRElUT1IsUk9MRV9PUElOSU9OX1BBTkVMX0VESVRPUixST0xFX1BBTkFST01BX0VESVRPUixST0xFX1BBTkVMX0RJU0NVU1NJT05fRURJVE9SLFJPTEVfUE9EQ0FTVF9FRElUT1IsUk9MRV9QUkFWQUhfRURJVE9SLFJPTEVfUklUQU1fTElWRV9FRElUT1IsUk9MRV9SSVRBTV9TVVBFUl9BRE1JTixST0xFX1NFV0FfRURJVE9SLFJPTEVfU1VCX0VESVRPUixST0xFX1ZJREVPX0JMT0dfRURJVE9SLFJPTEVfVklSQUxfVklERU9fRURJVE9SLFJPTEVfVklWSURIQV9FRElUT1IsUk9MRV9WWUFOR1lBX0VESVRPUixST0xFX1dJREdFVF9FRElUT1IiLCJleHAiOjE3MTk0MzE3MTR9.jsjPU0ADNTRm48ZJ-3v5kseE0Oa9bwqRD7oLeOfSIS6IPWdSX4Eh0YKxLh_PXACXbN7tS47kcNlOdbXm_uNxEQ'
}

def getCredentials():
    return {
        'username': os.environ['USERNAME'],
        'password': os.environ['PASSWORD']
    }